name: Build Arch Linux Package for lpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest # Use an Arch Linux container for makepkg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        pacman -Sy --noconfirm git base-devel gcc make libarchive curl openssl fmt

    - name: List files in lpkg/src
      run: |
        ls -l lpkg/src

    - name: Build lpkg
      run: |
        cd lpkg/src
        make

    - name: Upload lpkg artifact
      uses: actions/upload-artifact@v4
      with:
        name: lpkg
        path: lpkg/src/build/lpkg
